spring.application.name=auth-api

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# auth-api NO corre migraciones: el dueño del esquema es core-api
spring.flyway.enabled=false

server.port=${PORT:8081}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-minutes=60